const ADD_TODO = "ADD_TODO";
const TOGGLE_COMPLETED = "TOGGLE_COMPLETED";
const REMOVE_TODO = "REMOVE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const CHANGE_BTN_TEXT = "CHANGE_BTN_TEXT";
const UPDATE_ALL_TODOS = "UPDATE_ALL_TODOS"

export {
  ADD_TODO,
  TOGGLE_COMPLETED,
  REMOVE_TODO,
  UPDATE_TODO,
  CHANGE_BTN_TEXT,
  UPDATE_ALL_TODOS,
};
